# Site settings
title: CS371p Fall 2015 Min Bi
avatar: http://minbi.github.io/Bloggity/me.png
description: > # this means to ignore newlines until "baseurl:"
  An awesome description. Really just an everyday blog about OOP class.
baseurl: "/Bloggity" # the subpath of your site, e.g. /blog/
url: "http://minbi.github.io/" # the base hostname & protocol for your site
github_username:  minbi

# Build settings
markdown: kramdown
